-- Database-generated primary keys; existing IDs remain unchanged.
ALTER TABLE booking
    ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE guests
    ALTER COLUMN guest_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE service_charges
    ALTER COLUMN service_log_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Initialize each sequence above the existing records.
-- MAX is used once during migration, not for each new request.
SELECT setval(
    pg_get_serial_sequence('booking', 'booking_id'),
    GREATEST(COALESCE(MAX(booking_id), 0) + 1, 1),
    false
) FROM booking;

SELECT setval(
    pg_get_serial_sequence('guests', 'guest_id'),
    GREATEST(COALESCE(MAX(guest_id), 0) + 1, 1),
    false
) FROM guests;

SELECT setval(
    pg_get_serial_sequence('service_charges', 'service_log_id'),
    GREATEST(COALESCE(MAX(service_log_id), 0) + 1, 1),
    false
) FROM service_charges;
