import type {
  AvailabilityPayload,
  AvailabilityResponse,
  AmenitiesResponse,
  SendOTPResponse,
  VerifyOTPResponse,
  CreateBookingPayload,
  CreateBookingResponse,
} from './types';

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000';

// ─────────────────────────────────────────────
//  Generic request helper
// ─────────────────────────────────────────────
async function request<T>(
  path: string,
  options?: RequestInit
): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { 'Content-Type': 'application/json' },
    ...options,
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ message: `HTTP ${res.status}` }));
    throw new Error(body?.message ?? `Request failed with status ${res.status}`);
  }

  return res.json() as Promise<T>;
}

// ─────────────────────────────────────────────
//  Rooms / Availability
// ─────────────────────────────────────────────

/**
 * POST /api/v1/rooms/availability
 * Checks room availability for the given branch, dates, and guest count.
 * Returns real available rooms from the backend with prices and calculated totals.
 */
export async function checkAvailability(
  data: AvailabilityPayload
): Promise<AvailabilityResponse> {
  const params = new URLSearchParams();

  if (data.checkIn != null) params.set('check_in', data.checkIn);
  if (data.checkOut != null) params.set('check_out', data.checkOut);
  if (data.adults != null) params.set('adults', String(data.adults));
  if (data.children != null) params.set('children', String(data.children));
  if (data.branch != null) params.set('branch', data.branch);

  const query = params.toString();
  const url = `/api/v1/rooms${query ? `?${query}` : ''}`;

  return request<AvailabilityResponse>(url, { method: 'GET' });
}

// ─────────────────────────────────────────────
//  Amenities
// ─────────────────────────────────────────────

/**
 * GET /api/v1/amenities?branch=<branch>
 * Returns the list of add-on amenities available at this branch.
 */
export async function getAmenities(branch: string): Promise<AmenitiesResponse['amenities']> {
  const res = await request<AmenitiesResponse>(`/api/v1/amenities?branch=${encodeURIComponent(branch)}`);
  return res.amenities ?? [];
}

// ─────────────────────────────────────────────
//  OTP
// ─────────────────────────────────────────────

/**
 * POST /api/v1/otp/send
 * Sends an OTP SMS to the given phone number (+94 format).
 * Backend also performs a membership lookup at this stage.
 */
export async function sendOTP(phone: string): Promise<SendOTPResponse> {
  return request<SendOTPResponse>('/api/v1/otp/send', {
    method: 'POST',
    body: JSON.stringify({ phone }),
  });
}

/**
 * POST /api/v1/otp/verify
 * Verifies the OTP entered by the user.
 */
export async function verifyOTP(
  phone: string,
  otp: string
): Promise<VerifyOTPResponse> {
  return request<VerifyOTPResponse>('/api/v1/otp/verify', {
    method: 'POST',
    body: JSON.stringify({ phone, otp }),
  });
}

// ─────────────────────────────────────────────
//  Booking Creation
// ─────────────────────────────────────────────

/**
 * POST /api/v1/booking/create
 * Creates the confirmed booking record in the database.
 * Returns the unique booking reference generated by the backend.
 */
export async function createBooking(
  data: CreateBookingPayload
): Promise<CreateBookingResponse> {
  return request<CreateBookingResponse>('/api/v1/booking/create', {
    method: 'POST',
    body: JSON.stringify(data),
  });
}


