import type {
  AvailabilityPayload,
  AvailabilityResponse,
  AmenitiesResponse,
  SendOTPResponse,
  VerifyOTPResponse,
  CreateBookingPayload,
  CreateBookingResponse,
  StaffBooking,
  GuestProfile,
  ServiceCatalogueItem,
  InvoiceSummary,
  StaffUser,
  LoginResponse,
} from './types';

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000';

// ─────────────────────────────────────────────
//  Auth Token Helpers (Client-side)
// ─────────────────────────────────────────────
const TOKEN_KEY = 'skynest_auth_token';
const USER_KEY = 'skynest_auth_user';

export function getAuthToken(): string | null {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem(TOKEN_KEY);
}

export function getStoredUser(): StaffUser | null {
  if (typeof window === 'undefined') return null;
  const user = localStorage.getItem(USER_KEY);
  return user ? JSON.parse(user) : null;
}

export function setAuthSession(token: string, user: StaffUser) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(TOKEN_KEY, token);
  localStorage.setItem(USER_KEY, JSON.stringify(user));
}

export function clearAuthSession() {
  if (typeof window === 'undefined') return;
  localStorage.removeItem(TOKEN_KEY);
  localStorage.removeItem(USER_KEY);
}

// ─────────────────────────────────────────────
//  Generic request helper with Bearer token
// ─────────────────────────────────────────────
async function request<T>(
  path: string,
  options?: RequestInit
): Promise<T> {
  const token = getAuthToken();
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...((options?.headers as Record<string, string>) || {}),
  };

  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  const res = await fetch(`${BASE_URL}${path}`, {
    ...options,
    headers,
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ detail: `HTTP ${res.status}` }));
    throw new Error(body?.detail || body?.message || `Request failed with status ${res.status}`);
  }

  return res.json() as Promise<T>;
}

// ─────────────────────────────────────────────
//  Default / Hardcoded Room Types
// ─────────────────────────────────────────────
// ─────────────────────────────────────────────
//  Rooms / Availability
// ─────────────────────────────────────────────

/**
 * Checks room availability for the given branch, dates, and guest count.
 * Calls backend POST /api/v1/rooms/availability directly.
 */
export async function checkAvailability(
  data: AvailabilityPayload
): Promise<AvailabilityResponse> {
  return request<AvailabilityResponse>('/api/v1/rooms/availability', {
    method: 'POST',
    body: JSON.stringify({
      branch: data.branch,
      checkIn: data.checkIn,
      checkOut: data.checkOut,
      adults: data.adults,
      children: data.children,
    }),
  });
}




// ─────────────────────────────────────────────
//  OTP
// ─────────────────────────────────────────────

/**
 * POST /api/v1/otp/send
 * Sends an OTP SMS to the given phone number (+94 format).
 * Backend also performs a membership lookup at this stage.
 */
export async function sendOTP(phone: string): Promise<SendOTPResponse> {
  return request<SendOTPResponse>('/api/v1/otp/send', {
    method: 'POST',
    body: JSON.stringify({ phone }),
  });
}

/**
 * POST /api/v1/otp/verify
 * Verifies the OTP entered by the user.
 */
export async function verifyOTP(
  phone: string,
  otp: string
): Promise<VerifyOTPResponse> {
  return request<VerifyOTPResponse>('/api/v1/otp/verify', {
    method: 'POST',
    body: JSON.stringify({ phone, otp }),
  });
}

// ─────────────────────────────────────────────
//  Booking Creation
// ─────────────────────────────────────────────

/**
 * POST /api/v1/booking/create
 * Creates the confirmed booking record in the database.
 * Returns the unique booking reference generated by the backend.
 */
export async function createBooking(
  data: CreateBookingPayload
): Promise<CreateBookingResponse> {
  return request<CreateBookingResponse>('/api/v1/booking/create', {
    method: 'POST',
    body: JSON.stringify(data),
  });
}

// ─────────────────────────────────────────────
//  MANAGEMENT UI / RECEPTIONIST API
// ─────────────────────────────────────────────

/**
 * GET /api/v1/management/bookings
 * Retrieves all bookings for the active stays and booking management pages.
 */
export async function getAllBookings(): Promise<StaffBooking[]> {
  // Mock data since backend doesn't have management routes yet
  return [
    {
      bookingId: 1002,
      guestName: 'Test Guest',
      phone: '+94771234567',
      branchId: 1,
      bookingReference: 'BKG-1002',
      roomNumber: 101,
      roomType: 'Deluxe',
      checkIn: '2026-10-01',
      checkOut: '2026-10-05',
      status: 'Booked',
      adults: 2,
      children: 0
    },
    {
      bookingId: 1003,
      guestName: 'Kasun Perera',
      phone: '+94711112222',
      branchId: 1,
      bookingReference: 'BKG-1003',
      roomNumber: 205,
      roomType: 'Executive Suite',
      checkIn: '2026-09-28',
      checkOut: '2026-10-02',
      status: 'Checked-In',
      adults: 1,
      children: 0
    }
  ];
}

/**
 * POST /api/v1/management/bookings/:id/checkin
 * Checks in a guest (changes booking to Checked-In, Room to Occupied)
 */
export async function checkInGuest(bookingId: number): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Checked in' }), 500));
}

/**
 * POST /api/v1/management/bookings/:id/checkout
 * Checks out a guest (changes booking to Checked-Out). Fails if balance > 0.
 */
export async function checkOutGuest(bookingId: number): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Checked out' }), 500));
}

/**
 * GET /api/v1/management/bookings/:id/bill
 * Gets the current calculated bill for a booking.
 */
export async function getBill(bookingId: number): Promise<InvoiceSummary> {
  return new Promise(resolve => setTimeout(() => resolve({
    invoiceId: 'INV-001',
    bookingId,
    totalRoomCharges: 25000,
    totalAmenityCharges: 1500,
    totalServiceCharges: 5000,
    totalTaxAmount: 3000,
    grandTotal: 34500,
    amountPaid: 0,
    paymentStatus: 'Unpaid'
  }), 1000));
}

/**
 * POST /api/v1/management/bookings/:id/services
 * Adds a service to the guest's tab.
 */
export async function addServiceToBooking(bookingId: number, serviceId: number): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Service added' }), 500));
}

/**
 * POST /api/v1/management/bookings/:id/amenities
 * Adds an extra amenity to the guest's tab.
 */
export async function addAmenityToBooking(bookingId: number, amenityId: number): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Amenity added' }), 500));
}

/**
 * POST /api/v1/management/bookings/:id/extend
 * Extends the checkout date for a booking.
 */
export async function extendStay(bookingId: number, newCheckOutDate: string): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Stay extended' }), 500));
}

/**
 * POST /api/v1/management/memberships
 * Creates a new SkyNest Membership
 */
export async function createMembership(data: { name: string; phone: string; email: string }): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Membership created successfully' }), 800));
}

// ─────────────────────────────────────────────
//  Authentication API
// ─────────────────────────────────────────────
export async function loginStaff(username: string, password: string): Promise<LoginResponse> {
  const data = await request<LoginResponse>('/api/v1/auth/login', {
    method: 'POST',
    body: JSON.stringify({ username, password }),
  });
  setAuthSession(data.access_token, data.user);
  return data;
}

export async function fetchCurrentStaff(): Promise<StaffUser> {
  return request<StaffUser>('/api/v1/auth/me');
}
