import type {
  AvailabilityPayload,
  AvailabilityResponse,
  AmenitiesResponse,
  SendOTPResponse,
  VerifyOTPResponse,
  CreateBookingPayload,
  CreateBookingResponse,
  StaffBooking,
  BookingStatus,
  GuestProfile,
  ServiceCatalogueItem,
  InvoiceSummary,
  StaffUser,
  LoginResponse,
} from './types';

const BASE_URL = typeof window !== 'undefined' ? (process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000') : (process.env.INTERNAL_API_URL ?? 'http://backend:8000');

// ─────────────────────────────────────────────
//  Auth Token Helpers (Client-side)
// ─────────────────────────────────────────────
const TOKEN_KEY = 'skynest_auth_token';
const USER_KEY = 'skynest_auth_user';

export function getAuthToken(): string | null {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem(TOKEN_KEY);
}

export function getStoredUser(): StaffUser | null {
  if (typeof window === 'undefined') return null;
  const user = localStorage.getItem(USER_KEY);
  return user ? JSON.parse(user) : null;
}

export function setAuthSession(token: string, user: StaffUser) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(TOKEN_KEY, token);
  localStorage.setItem(USER_KEY, JSON.stringify(user));
}

export function clearAuthSession() {
  if (typeof window === 'undefined') return;
  localStorage.removeItem(TOKEN_KEY);
  localStorage.removeItem(USER_KEY);
}

// ─────────────────────────────────────────────
//  Generic request helper with Bearer token
// ─────────────────────────────────────────────
async function request<T>(
  path: string,
  options?: RequestInit
): Promise<T> {
  const staffToken = getAuthToken();
  const guestToken = typeof window !== 'undefined' ? localStorage.getItem('guest_token') : null;
  const token = staffToken || guestToken;

  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...((options?.headers as Record<string, string>) || {}),
  };

  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  const res = await fetch(`${BASE_URL}${path}`, {
    ...options,
    headers,
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ detail: `HTTP ${res.status}` }));
    throw new Error(body?.detail || body?.message || `Request failed with status ${res.status}`);
  }

  return res.json() as Promise<T>;
}

// ─────────────────────────────────────────────
//  Default / Hardcoded Room Types
// ─────────────────────────────────────────────
// ─────────────────────────────────────────────
//  Rooms / Availability
// ─────────────────────────────────────────────

/**
 * Checks room availability for the given branch, dates, and guest count.
 * Calls backend POST /api/v1/rooms/availability directly.
 */
export async function checkAvailability(
  data: AvailabilityPayload
): Promise<AvailabilityResponse> {
  const res = await request<AvailabilityResponse>('/api/v1/rooms/availability', {
    method: 'POST',
    body: JSON.stringify({
      branch: data.branch,
      checkIn: data.checkIn,
      checkOut: data.checkOut,
      adults: data.adults,
      children: data.children,
    }),
  });
  const hasMembership = typeof window !== 'undefined' ? !!localStorage.getItem('guest_token') : false;
  return {
    ...res,
    hasMembership: res.hasMembership ?? hasMembership,
  };
}



// ─────────────────────────────────────────────
//  OTP
// ─────────────────────────────────────────────

/**
 * POST /api/v1/otp/send
 * Sends an OTP SMS to the given phone number (+94 format).
 * Backend also performs a membership lookup at this stage.
 */
export async function sendOTP(phone: string): Promise<SendOTPResponse> {
  return request<SendOTPResponse>('/api/v1/otp/send', {
    method: 'POST',
    body: JSON.stringify({ phone }),
  });
}

/**
 * POST /api/v1/otp/verify
 * Verifies the OTP entered by the user.
 */
export async function verifyOTP(
  phone: string,
  otp: string
): Promise<VerifyOTPResponse> {
  return request<VerifyOTPResponse>('/api/v1/otp/verify', {
    method: 'POST',
    body: JSON.stringify({ phone, otp }),
  });
}

// ─────────────────────────────────────────────
//  Booking Creation
// ─────────────────────────────────────────────

/**
 * POST /api/v1/booking/create
 * Creates the confirmed booking record in the database.
 * Returns the unique booking reference generated by the backend.
 */
export async function createBooking(
  data: CreateBookingPayload
): Promise<CreateBookingResponse> {
  return request<CreateBookingResponse>('/api/v1/bookings/', {
    method: 'POST',
    body: JSON.stringify(data),
  });
}

/**
 * GET /api/v1/bookings/?status=Checked-In
 * Fetches all guests who are currently checked in (Active Stays).
 */
export async function getActiveStays(): Promise<any[]> {
  return request<any[]>('/api/v1/bookings/?status=Checked-In', {
    method: 'GET',
  });
}

/**
 * POST /api/v1/bookings/{booking_id}/services
 * Adds a service to the guest's tab.
 */
export async function addServiceToTab(bookingId: number, serviceName: string, serviceTotal: number): Promise<any> {
  return request<any>(`/api/v1/bookings/${bookingId}/services`, {
    method: 'POST',
    body: JSON.stringify({
      service_name: serviceName,
      service_total: serviceTotal,
      service_dates: 1
    }),
  });
}

/**
 * GET /api/v1/booking/
 * Gets the reservations for the authenticated guest
 */
export async function getMyBookings(): Promise<StaffBooking[]> {
  const raw = await request<Array<{
    booking_id: number;
    guest_name: string;
    room_number: number;
    branch_name: string;
    booking_status: string;
    start_date: string;
    end_date: string;
  }>>('/api/v1/booking/');

  return raw.map(b => ({
    bookingId: b.booking_id,
    guestName: b.guest_name,
    phone: '',
    branchId: 0,
    bookingReference: `BKG-${b.booking_id}`,
    roomNumber: b.room_number,
    roomType: '',
    checkIn: b.start_date,
    checkOut: b.end_date,
    status: b.booking_status as BookingStatus,
    adults: 0,
    children: 0,
  }));
}

// ─────────────────────────────────────────────
//  MANAGEMENT UI / RECEPTIONIST API
// ─────────────────────────────────────────────

/**
 * GET /api/v1/private/bookings/admin-reservations
 */
export async function getAdminReservationsList(status?: string): Promise<any[]> {
  const url = status 
    ? `/api/v1/private/bookings/admin-reservations?status=${encodeURIComponent(status)}`
    : '/api/v1/private/bookings/admin-reservations';
  return request<any[]>(url, { method: 'GET' });
}

/**
 * GET /api/v1/bookings/
 * Retrieves all bookings. Maps backend BookingListItem → frontend StaffBooking.
 */
export async function getAllBookings(): Promise<StaffBooking[]> {
  const raw = await request<Array<{
    booking_id: number;
    guest_name: string;
    room_number: number;
    branch_name: string;
    booking_status: string;
    start_date: string;
    end_date: string;
  }>>('/api/v1/bookings/');

  return raw.map(b => ({
    bookingId: b.booking_id,
    guestName: b.guest_name,
    phone: '',
    branchId: 0,
    bookingReference: `BKG-${b.booking_id}`,
    roomNumber: b.room_number,
    roomType: '',
    checkIn: b.start_date,
    checkOut: b.end_date,
    status: b.booking_status as BookingStatus,
    adults: 0,
    children: 0,
  }));
}

/**
 * GET /api/v1/bookings/{id}
 * Gets full booking details including services and invoice.
 */
export async function getBookingDetail(bookingId: number): Promise<InvoiceSummary> {
  const b = await request<{
    booking_id: number;
    booking_status: string;
    service_charges: Array<{ service_name: string; service_total: number }>;
    invoice_status: string;
    grand_total: number;
    amount_paid: number;
  }>(`/api/v1/bookings/${bookingId}`);

  const totalServiceCharges = b.service_charges.reduce((sum, s) => sum + s.service_total, 0);

  return {
    invoiceId: `INV-${bookingId}`,
    bookingId: b.booking_id,
    totalRoomCharges: b.grand_total - totalServiceCharges,
    totalAmenityCharges: 0,
    totalServiceCharges,
    totalTaxAmount: 0,
    grandTotal: b.grand_total,
    amountPaid: b.amount_paid,
    paymentStatus: b.invoice_status as 'Paid' | 'Partial' | 'Unpaid',
  };
}

/**
 * POST /api/v1/bookings/{id}/check-in
 * Checks in a guest (changes booking to Checked-In, Room to Occupied)
 */
export async function checkInGuest(bookingId: number): Promise<{ success: boolean; message: string }> {
  try {
    await request(`/api/v1/bookings/${bookingId}/check-in`, { method: 'POST' });
    return { success: true, message: 'Guest checked in successfully' };
  } catch (e: any) {
    return { success: false, message: e.message ?? 'Check-in failed' };
  }
}

/**
 * POST /api/v1/bookings/{id}/check-out
 * Checks out a guest. Enforces full invoice payment before checkout.
 */
export async function checkOutGuest(bookingId: number): Promise<{ success: boolean; message: string }> {
  try {
    await request(`/api/v1/bookings/${bookingId}/check-out`, { method: 'POST' });
    return { success: true, message: 'Guest checked out successfully' };
  } catch (e: any) {
    return { success: false, message: e.message ?? 'Check-out failed' };
  }
}

/**
 * GET /api/v1/bookings/{id}/bill  (uses getBookingDetail internally)
 */
export async function getBill(bookingId: number): Promise<InvoiceSummary> {
  return getBookingDetail(bookingId);
}

/**
 * POST /api/v1/bookings/{id}/cancel
 */
export async function cancelBooking(bookingId: number): Promise<{ success: boolean; message: string }> {
  try {
    await request(`/api/v1/bookings/${bookingId}/cancel`, { method: 'POST' });
    return { success: true, message: 'Booking cancelled' };
  } catch (e: any) {
    return { success: false, message: e.message ?? 'Cancellation failed' };
  }
}

// These endpoints are not yet implemented in the backend — kept as stubs
export async function addServiceToBooking(bookingId: number, serviceId: number): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Service added' }), 500));
}

export async function addAmenityToBooking(bookingId: number, amenityId: number): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Amenity added' }), 500));
}

export async function extendStay(bookingId: number, newCheckOutDate: string): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Stay extended' }), 500));
}

/**
 * POST /api/v1/management/memberships
 * Creates a new SkyNest Membership (stub — backend not yet implemented)
 */
export async function createMembership(data: { name: string; phone: string; email: string }): Promise<{ success: boolean; message: string }> {
  return new Promise(resolve => setTimeout(() => resolve({ success: true, message: 'Membership created successfully' }), 800));
}

// ─────────────────────────────────────────────
//  Authentication API
// ─────────────────────────────────────────────
export async function loginStaff(username: string, password: string): Promise<LoginResponse> {
  const data = await request<LoginResponse>('/api/v1/auth/login', {
    method: 'POST',
    body: JSON.stringify({ username, password }),
  });
  setAuthSession(data.access_token, data.user);
  return data;
}

export async function fetchCurrentStaff(): Promise<StaffUser> {
  return request<StaffUser>('/api/v1/auth/me');
}

// ─────────────────────────────────────────────
//  ADMIN API
// ─────────────────────────────────────────────

/**
 * GET /api/v1/rooms/all
 * Returns all rooms in the hotel.
 */
export async function getAllRooms(): Promise<any[]> {
  return request('/api/v1/rooms/all');
}

/**
 * GET /api/v1/branches/
 * Returns all hotel branches.
 */
export async function getBranches(): Promise<Array<{ branch_id: number; branch_name: string }>> {
  return request('/api/v1/branches/');
}

/**
 * GET /api/v1/reports/monthly-revenue?year=YYYY
 * Returns monthly revenue breakdown per branch for a given year.
 */
export async function getMonthlyRevenue(year: number): Promise<{
  year: number;
  data: Array<{ branch_name: string; month: string; room_revenue: number; service_revenue: number; total_revenue: number }>;
}> {
  return request(`/api/v1/reports/monthly-revenue?year=${year}`);
}

/**
 * GET /api/v1/reports/occupancy?start_date=YYYY-MM-DD&end_date=YYYY-MM-DD
 * Returns occupancy rate per branch for a given period.
 */
export async function getOccupancyReport(startDate: string, endDate: string): Promise<{
  period: { start_date: string; end_date: string };
  branches: Array<{ branch_name: string; total_rooms: number; occupied_nights: number; total_possible_nights: number; occupancy_rate_percent: number }>;
}> {
  return request(`/api/v1/reports/occupancy?start_date=${startDate}&end_date=${endDate}`);
}

/**
 * GET /api/v1/services/
 * Returns all services.
 */
export async function getServices(): Promise<Array<{ service_id: number; service_name: string; day_rate: number; description: string }>> {
  return request('/api/v1/services/');
}

/**
 * GET /api/v1/guests/
 * Returns all guests.
 */
export async function getGuests(): Promise<Array<{ guest_id: number; name: string; national_id: string; phone_number: string; membership_id: number | null }>> {
  return request('/api/v1/guests/');
}

/**
 * GET /api/v1/amenities
 * Returns all amenities.
 */
export async function getAmenities(): Promise<Array<{ id: number; name: string; price: number }>> {
  return request('/api/v1/amenities');
}
